# -*- coding: utf-8 -*-
"""NASA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQPxl09MDQWKEdCcVtNyTegFDbryHx-c
"""

import pandas as pd
import numpy as np
lunar_df = pd.read_csv("lunar.csv")
lunar_df

lunar_df.head()

lunar_df["Eclipse Type"].value_counts()

lunar_df["Quincena Solar Eclipse"].unique()

lunar_df.drop_duplicates(inplace=True)
lunar_df.dropna()
lunar_df.info()

# Total eclipse duration vs eclipse type
lunar_df.groupby("Eclipse Type")["Total Eclipse Duration (m)"].count().plot.bar()

import matplotlib.pyplot as plt
lunar_df = pd.read_csv("lunar.csv")
eclipse_type_counts = lunar_df["Eclipse Type"].value_counts()
print("Counts of each Eclipse Type:")
print(eclipse_type_counts)
eclipse_type_counts.plot(kind="bar", color="skyblue", title="Counts of Each Eclipse Type")
plt.xlabel("Eclipse Type")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

quincena_counts = lunar_df["Gamma"].value_counts()
quincena_counts.plot(kind="bar", color="lightgreen", title="Counts of Quincena Solar Eclipses by Gamma Value")
plt.xlabel("Gamma Value")
plt.ylabel("Count")
plt.show()